/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panes;
import models.Conection;    
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Conection;

/**
 *
 * @author james
 */
public class Productos extends javax.swing.JPanel {

    Conection cn1 = new Conection();
    Connection con1;
    DefaultTableModel modTable;
    Statement state;
    ResultSet res;
    public Productos() {
        initComponents();
        Rellenar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        Btnmod = new javax.swing.JButton();
        Btnreg = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtBarcode = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TxtSiniva = new javax.swing.JTextField();
        TxtConiva = new javax.swing.JTextField();
        Txtdesc = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TxtBuscar = new javax.swing.JTextField();
        Btnbuscar = new javax.swing.JButton();

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cod. Barras", "Descripción", "Precio Base", "Precio IVA"
            }
        ));
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Registro Productos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Btnmod.setText("Modificar");
        Btnmod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnmodMouseClicked(evt);
            }
        });
        jPanel1.add(Btnmod, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        Btnreg.setText("Registrar");
        jPanel1.add(Btnreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 80, -1));

        jLabel5.setText("Precio con IVA");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jLabel4.setText("Precio sin IVA");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));
        jPanel1.add(TxtBarcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 120, -1));

        jLabel1.setText("Cod. Barras");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));
        jPanel1.add(TxtSiniva, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 100, -1));
        jPanel1.add(TxtConiva, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 100, -1));

        Txtdesc.setColumns(20);
        Txtdesc.setRows(5);
        jPanel1.add(Txtdesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel3.setText("Descripción Prod.");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));
        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(796, 46, -1, -1));

        jLabel2.setText("$");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel6.setText("$");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, 20));

        Btnbuscar.setText("Buscar");
        Btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnbuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(TxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btnbuscar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btnbuscar, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        int fila = Tabla.getSelectedRow();
        if(fila == -1){
            JOptionPane.showMessageDialog(null, "No se ha seleccionado ningún dato.");
        }else{
            int bar = Integer.parseInt((String) Tabla.getValueAt(fila,0) .toString());
            String desc = (String) Tabla.getValueAt(fila, 1);
            double sinIva = Integer.parseInt((String) Tabla.getValueAt(fila,2) .toString());
            double conIva = Integer.parseInt((String) Tabla.getValueAt(fila,3) .toString());
            
            TxtBarcode.setText(""+bar);
            Txtdesc.setText(desc);
            TxtSiniva.setText(""+ sinIva);
            TxtConiva.setText(""+ conIva);
        }
    }//GEN-LAST:event_TablaMouseClicked

    private void BtnmodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnmodMouseClicked
        int barcode;
        double coniva, siniva;
        String desc;
        
        barcode = Integer.parseInt(TxtBarcode.getText().trim());
        coniva = Integer.parseInt(TxtConiva.getText().trim());
        siniva = Integer.parseInt(TxtSiniva.getText().trim());
        desc = Txtdesc.getText().trim();
        
        String prod = "UPDATE productos SET Descripcion = '"+ desc +"', Precio_sin_iva = '"+ siniva +"', Precio_sin_iva = '"+ siniva +"' ";
        try{
            Connection cn = Conection.Conection();
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(prod);
            cn.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error al Ingresar los datos \n \n Vuelva a intentarlo más tarde.");
        }
    }//GEN-LAST:event_BtnmodMouseClicked

    private void BtnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnbuscarActionPerformed
        buscar(TxtBuscar.getText());
    }//GEN-LAST:event_BtnbuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btnbuscar;
    private javax.swing.JButton Btnmod;
    private javax.swing.JButton Btnreg;
    private javax.swing.JTable Tabla;
    private javax.swing.JTextField TxtBarcode;
    private javax.swing.JTextField TxtBuscar;
    private javax.swing.JTextField TxtConiva;
    private javax.swing.JTextField TxtSiniva;
    private javax.swing.JTextArea Txtdesc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
    
    void Rellenar(){
        String sql = "SELECT Cod_barra, Descripcion, Precio_sin_iva, Precio_con_iva FROM productos";
        try{
            con1 = cn1.Conection();
            state = con1.createStatement();
            res = state.executeQuery(sql);
            Object[]Productos = new Object[4];
            modTable = (DefaultTableModel) Tabla.getModel();
            while(res.next()){
                Productos[0] = res.getInt("Cod_barra");
                Productos[1] = res.getString("Descripcion");
                Productos[2] = res.getString("Precio_sin_iva");
                Productos[3] = res.getString("Precio_con_iva");
                
                modTable.addRow(Productos);
            }
            Tabla.setModel(modTable);
            con1.close();
        }catch(Exception e){
            
        }
    }
    
    public DefaultTableModel buscar(String buscar){
        String[] nombreRow = {"Cod", "Descripcion", "Precio", "Precio +IVA"};
        Object[]Productos = new Object[4];
        DefaultTableModel mod = new DefaultTableModel(null, nombreRow);
        
        String view = "SELECT Cod_barra, Descripcion, Precio_sin_iva, Precio_con_iva FROM productos WHERE Cod_barra LIKE '%" + buscar + "%' OR Descripcion LIKE '%" + buscar + "%'";
        
        try{
            con1 = cn1.Conection();
            state = con1.createStatement();
            res = state.executeQuery(view);
            while(res.next()){
                
                Productos[0] = res.getInt("Cod_barra");
                Productos[1] = res.getString("Descripcion");
                Productos[2] = res.getDouble("Precio_sin_iva");
                Productos[3] = res.getDouble("Precio_con_iva");
                
            }
            con1.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error de busqueda. \n \n Vuelva a Intentarlo.");
        }
        return mod;
        
    }
}
